# ansible-configured
---
##############################################################################
# SERVERS: Install and configure timezone
##############################################################################
- hosts: servers
  name: servers set timezone to UTC
  gather_facts: True
  become: yes
  become_method: sudo
  environment:
    DEBIAN_FRONTEND: noninteractive
  tags:
    - servers
    - install
    - servers_install
    - timezone

  roles:
    - role: ../
