# ansible-configured
---
##############################################################################
# SERVERS: Install and configure timezone
##############################################################################
- hosts: servers
  name: servers set timezone to America/New_York
  gather_facts: True
  become: yes
  become_method: sudo
  environment:
    DEBIAN_FRONTEND: noninteractive

  roles:
    - role: ../
      timezone: 'America/New_York'
      tags:
        - boss-ansible-role-timezone

    - role: boss-ansible-role-debug
      boss__debug__debug_variables_file: '/tmp/ansible_variables'
      boss__debug__dump_dir: '/etc/ansible_dumps'
      boss__debug__dump_type: 'seperate' # seperate
      tags:
        - boss-ansible-role-debug
