---
# handlers file for ansible-timezone
- name: update tzdata
  command: "dpkg-reconfigure --frontend noninteractive tzdata"


- name: restart systemd-timesyncd
  service:
    name: "systemd-timesyncd"
    state: "restarted"
  become: true
  when: not ansible_check_mode


- name: restart cron
  service:
    name: "cron"
    state: "restarted"
  become: true
  when: not ansible_check_mode
